import type { Metadata } from "next";
import "./globals.css";
import { mena, p22, satoshi, p22800, satoshiBold } from "./fonts";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
        className={`${mena.variable} ${p22.variable} ${satoshi.variable} ${satoshiBold.variable} ${p22800.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
