import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { mena, p22, satoshi } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mena.variable} ${p22.variable} ${satoshi.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
